branches:
  only:
  - v02 

language: cpp

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
    - xorg-dev  

before_script:
  - sudo apt-get install -y xpra xserver-xorg-video-dummy freeglut3-dev
  - mkdir build
  - cd build
  - cmake ../examples/demo-app/

script: make
