branches:
  only:
  - v02 

language: cpp

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
    - xorg-dev  

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - mkdir build
  - cd build
  - cmake ../examples/demo-app/

script: make
